const caixaPerguntas = document.querySelector(".caixa-perguntas");
const caixaAlternativas = document.querySelector(".caixa-alternativas");
const caixaResultado = document.querySelector(".caixa-resultado");
const textoResultado = document.querySelector(".texto-resultado");

const perguntas = [
  {
      enunciado: "Qual o verdadeiro nome do Homem de Ferro?",
          alternativas: [
                { texto: "Steve Rogers", correta: false },
                      { texto: "Tony Stark", correta: true },
                            { texto: "Tony Sterco", correta: false },
                                ]
                                  },
                                    {
                                        enunciado: "Qual é o nome do martelo mágico do Thor?",
                                            alternativas: [
                                                  { texto: "Stormbreaker", correta: false },
                                                        { texto: "Mjolnir", correta: true },
                                                              { texto: "Jhonatan", correta: false }
                                                                  ]
                                                                    },
                                                                      {
                                                                          enunciado: "Quem é o rei de Wakanda?",
                                                                              alternativas: [
                                                                                    { texto: "T'Challa", correta: true },
                                                                                          { texto: "Killmonger", correta: false },
                                                                                                { texto: "M'Baku", correta: false }
                                                                                                    ]
                                                                                                      },
                                                                                                        {
                                                                                                            enunciado: "Qual Vilao conseguiu 'derrotar'os vingadores?"
                                                                                                                alternativas: [
                                                                                                                      { texto: "Thanos", correta: true },
                                                                                                                            { texto: "Ultron", correta: false },
                                                                                                                                  { texto: "Loki", correta: false }
                                                                                                                                      ]
                                                                                                                                        },
                                                                                                                                          {
                                                                                                                                              enunciado: "Quem é a irmã da Wanda Maximoff?",
                                                                                                                                                  alternativas: [
                                                                                                                                                        { texto: "Ela não tem irmã", correta: true },
                                                                                                                                                              { texto: "Natasha Romanoff", correta: false },
                                                                                                                                                                    { texto: "Gamora", correta: false }
                                                                                                                                                                        ]
                                                                                                                                                                          },
                                                                                                                                                                            {
                                                                                                                                                                                enunciado: "Em qual filme aparece o Doutor Estranho pela primeira vez?",
                                                                                                                                                                                    alternativas: [
                                                                                                                                                                                          { texto: "Gente Grande", correta: false },
                                                                                                                                                                                                { texto: "Doutor Estranho (2016)", correta: true },
                                                                                                                                                                                                      { texto: "Homem Aranha 2", correta: false }
                                                                                                                                                                                                          ]
                                                                                                                                                                                                            },
                                                                                                                                                                                                              {
                                                                                                                                                                                                                  enunciado: "Quem é o soldado invernal?",
                                                                                                                                                                                                                      alternativas: [
                                                                                                                                                                                                                            { texto: "Bucky Barnes", correta: true },
                                                                                                                                                                                                                                  { texto: "Sam Wilson", correta: false },
                                                                                                                                                                                                                                        { texto: "Steve Roggers", correta: false },
                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                    enunciado: "Qual foi o primeiro filme da Marvel Studios?",
                                                                                                                                                                                                                                                        alternativas: [
                                                                                                                                                                                                                                                              { texto: "Homem-Aranha", correta: false },
                                                                                                                                                                                                                                                                    { texto: "Homem de Ferro (2008)", correta: true },
                                                                                                                                                                                                                                                                          { texto: "Hulk", correta: false }
                                                                                                                                                                                                                                                                              ]
                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                      enunciado: "Quem criou o Ultron?",
                                                                                                                                                                                                                                                                                          alternativas: [
                                                                                                                                                                                                                                                                                                { texto: "Bruce Banner e Tony Stark", correta: true },
                                                                                                                                                                                                                                                                                                      { texto: "Nick Fury", correta: false },
                                                                                                                                                                                                                                                                                                            { texto: "Thanos", correta: false }
                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                        enunciado: "Qual o nome verdadeiro da Viúva Negra?",
                                                                                                                                                                                                                                                                                                                            alternativas: [
                                                                                                                                                                                                                                                                                                                                  { texto: "Natasha Romanoff", correta: true },
                                                                                                                                                                                                                                                                                                                                        { texto: "Carol Danvers", correta: false },
                                                                                                                                                                                                                                                                                                                                              { texto: "Vitoria Lira", correta: false }
                                                                                                                                                                                                                                                                                                                                                  ]
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                    ];

                                                                                                                                                                                                                                                                                                                                                    let atual = 0;
                                                                                                                                                                                                                                                                                                                                                    let pontos = 0;

                                                                                                                                                                                                                                                                                                                                                    function mostraPergunta() {
                                                                                                                                                                                                                                                                                                                                                      if (atual >= perguntas.length) {
                                                                                                                                                                                                                                                                                                                                                          mostraResultado();
                                                                                                                                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                  const perguntaAtual = perguntas[atual];
                                                                                                                                                                                                                                                                                                                                                                    caixaPerguntas.textContent = perguntaAtual.enunciado;
                                                                                                                                                                                                                                                                                                                                                                      caixaAlternativas.textContent = "";

                                                                                                                                                                                                                                                                                                                                                                        perguntaAtual.alternativas.forEach(alternativa => {
                                                                                                                                                                                                                                                                                                                                                                            const botao = document.createElement("button");
                                                                                                                                                                                                                                                                                                                                                                                botao.textContent = alternativa.texto;
                                                                                                                                                                                                                                                                                                                                                                                    botao.addEventListener("click", () => respostaSelecionada(alternativa.correta));
                                                                                                                                                                                                                                                                                                                                                                                        caixaAlternativas.appendChild(botao);
                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                          function respostaSelecionada(correta) {
                                                                                                                                                                                                                                                                                                                                                                                            if (correta) {
                                                                                                                                                                                                                                                                                                                                                                                                pontos++;
                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                    atual++;
                                                                                                                                                                                                                                                                                                                                                                                                      mostraPergunta();
                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                      function mostraResultado() {
                                                                                                                                                                                                                                                                                                                                                                                                        caixaPerguntas.textContent = "Fim do Quiz!";
                                                                                                                                                                                                                                                                                                                                                                                                          textoResultado.textContent = "Você acertou " + pontos + " de " + perguntas.length + " perguntas.";
                                                                                                                                                                                                                                                                                                                                                                                                            caixaAlternativas.textContent = "";
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                            mostraPergunta();
